#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying app with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

cd /Users/thomas/Projects/thomasmcevoy.github.io
npm run build
git add .
git commit -m "$1"
git push
